feat: Import new contracts-v2 beta
across-protocol/sdk-v2 pull request #541
Opened 2024-02-09 00:10 UTC by pxrl

This change imports the new contracts-v2 package, aliased under contracts-v2-beta. It can be used side-by-side with the existing contracts-v2.

2024-02-09 14:14 UTC, pxrl commented on package.json
> +    "@across-protocol/contracts-v2": "^2.4.8",
For reference, the delta from v2.4.7 to v2.4.8 is this commit: https://github.com/across-protocol/contracts-v2/commit/65a007c5e6dbb51b1a54b770f246d2002dafb1b0

2024-02-09 14:21 UTC, nicholaspai approved these changes

2024-02-09 14:21 UTC, pxrl commented
The follow-up PR here shows how this can be used: https://github.com/across-protocol/sdk-v2/pull/545

2024-02-09 16:46 UTC, nicholaspai requested changes
I think there's an issue with this approach. It doesn't test the clients against the realistic scenario where a single spoke pool emits both V2 and V3 events. This PR instead tests the clients against V2 and V3 events in isolation but there might be regressions when combined. I think a better approach with low code diff is to modify the contracts-v2 code exported out of dir/test-utils to handle this

2024-02-09 19:14 UTC, nicholaspai commented
I recommend closing this in favor of https://github.com/across-protocol/sdk-v2/pull/546 which uses an updated contracts-v2 import with a depositV2 function https://github.com/across-protocol/contracts-v2/pull/429

2024-02-11 22:47 UTC, closed without merging

2024-02-11 22:47 UTC, pxrl commented
Closed in favour of https://github.com/across-protocol/sdk-v2/commit/04be89449dd177d6c58385dd5f6af62cf089ef90